language: node_js
node_js:
  - 15

services:
  - docker

before_install:
  - docker build -t paperplanemove/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true paperplanemove/docker-react npm run test